// <auto-generated />
namespace Mlb5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddLots : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLots));
        
        string IMigrationMetadata.Id
        {
            get { return "201610280423455_AddLots"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
